name = "PlainLinearAlgebra"
uuid = "53025de0-f5aa-11e8-33f3-17339071e9ec"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com>"]
version = "0.1.0"

[deps]
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
